---

- hosts: webservers

  become: yes

  tasks:
  
  - name: NGINX INSTALLATION

    apt:

      name: nginx

      state: present

      update_cache: true
    notify:

    - start nginx

  - name: PHP INSTALLATION

    apt:

      name: php

      state: present

      update_cache: true



  - name: PHP-FPM INSTALLATION

    apt:

      name: php-fpm

      state: present

      update_cache: true

    notify:

    - start php7.4-fpm

  
  - name: SETS NGINX CONF FILE 
    template:
       src: "./Nginx.conf"
       dest: "/etc/nginx/nginx.conf"
    notify:
    - restart php7.4-fpm
    - restart nginx

  - name: REMOVE NGINX CONF
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent
    notify: 
    - restart nginx

  - name: RUNNING NGINX CONF
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: CHANGING DEFAULT FILE 
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link
    notify: 
    - restart nginx
   
  - name: SETTING INDEX.PHP WEBPAGE 
    template:
      src: "./index.php"
      dest: "/var/www/html/index.php"
    notify:
    - restart nginx
    - start nginx
    - restart php7.4-fpm
    - start php7.4-fpm 


  handlers:

  - name: start php7.4-fpm
    service:

      name: php7.4-fpm

      state: started



  - name: start nginx
    service:

      name: nginx

      state: started


  - name: restart php7.4-fpm
    service:

      name: php7.4-fpm

      state: restarted
  - name: restart nginx

    service:

      name: nginx

      state: restarted
- hosts: haproxy
  become: yes

  tasks:
  


  - name: HAPROXY INSTALLATION ON DEVHAPROXY 
    apt:
      name: haproxy
      state: present
      update_cache: true

  - name: CHANGING HAPROXY CONFIGURATION 
    template:
      src: ./haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
      mode: 0640
      owner: root
      group: root
    notify:
    - restart haproxy
    
  - name: ENABLING HAPROXY 
    lineinfile:
      dest: /etc/default/haproxy
      regexp: "^ENABLED"
      line: "ENABLED=1"
    notify:
    - restart haproxy


  handlers:
  
  - name: restart haproxy
    service:
        name: haproxy
        state: restarted

   
...
